### ISSUE TITLE
es6

### ISSUE THREAD

**Issue by chrvadala** [nidu/svg-transform-parser#1]
Hi @nidu ,
I'm the author of transformation-matrix https://github.com/chrvadala/transformation-matrix. A library that allows to work with transformations matrices using ES6 syntax. 
I see that you made a pegjs descriptor that is able to parse a css transformation string https://github.com/nidu/svg-transform-parser/blob/master/parse-svg-transform.pegjs. I'd like to use that descriptor to generate an es6 module and include it in mine library. Is it an option for you? I see that you are no longer working on that project.

**Comment by nidu** [comment]
Hello @chrvadala 
Sure, you can take the descriptor, but this library is probably not well tested, so please check twice if the code is ok for you.

**Comment by chrvadala** [comment]
Thanks nidu,
I will cite you as contributor of transformation-matrix. 
I'm going to give a new life to this pegjs descriptor.
Good luck with your projects
